/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SushiCall } from "./SushiCall";

export { SushiCall__factory } from "./factories/SushiCall__factory";
